#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */
defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');

require(__DIR__ . '/vendor/autoload.php');
require(__DIR__ . '/vendor/albert/yii2-swoole/Yii.php');
require(__DIR__ . '/common/config/bootstrap.php');
require(__DIR__ . '/console/config/bootstrap.php');

$config = yii\helpers\ArrayHelper::merge(
    require(__DIR__ . '/common/config/main-dev.php'), require(__DIR__ . '/common/config/main-local.php'), require(__DIR__ . '/console/config/main-dev.php'), require(__DIR__ . '/console/config/main-local.php')
);

$application = new \yii\swoole\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
